Upgrade dependencies
sagarkarki99/simple_push_notification pull request #8
Opened 2024-08-01 14:02 UTC by palvajk

Upgrade the dependencies because of the old firebase_core package

2024-08-02 07:16 UTC, sagarkarki99 requested changes
Can you also upgrade the sdk version to `>=3.2.0 <4.0.0`, @palvajk ? The latest version of `firebase_messaging` requires sdk version more than `3.2.0`.

2024-08-02 07:28 UTC, palvajk commented
@sagarkarki99 Ahh sure, I updated!

2024-09-12 08:20 UTC, radikris commented
@sagarkarki99 I would really appreciate if you could merge this pr :)

2025-03-18 06:11 UTC, C4st3ll4n commented
Still no update ??

2025-03-18 07:19 UTC, sagarkarki99 approved these changes

2025-03-18 07:20 UTC, merged